# Generated by Django 4.2.7 on 2024-05-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_topic_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Коментар до відео')),
                ('video', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/', verbose_name='Відео')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання відео')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
            options={
                'verbose_name_plural': 'Відео',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Коментар до фото')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Фото')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
            options={
                'verbose_name_plural': 'Фото по темам',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Коментар до файлу')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання файлу')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
            options={
                'verbose_name_plural': 'Файли',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Коментар до аудіо')),
                ('audio', models.FileField(blank=True, upload_to='audios/%Y/%m/%d/', verbose_name='Аудіо')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання аудіо')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
            options={
                'verbose_name_plural': 'Аудіо',
            },
        ),
    ]
